version: 2

sources:
  - name: staging
    database: boston-blue-bikes
    schema: staging

    tables:
      - name: tripdata
      - name: stationdata_status
      - name: stationdata_information
      - name: regions
    

models:
  - name: trips
  - name: stationdata_info_most_recent
  - name: stationdata_status_most_recent
