version: 2

sources:
  - name: staging
    database: boston-blue-bikes
    loader: gcloud storage

    tables:
      - name: tripdata
        external:
          location: 'gs://boston_blue_bikes_data_lake/data/tripdata/*.parquet' 
          options:
            format: PARQUET
    
      - name: stationdata_status
        external:
          location: 'gs://boston_blue_bikes_data_lake/data/stationdata/station_status-*.parquet'
          options:
            format: PARQUET

      - name: stationdata_information
        external:
          location: 'gs://boston_blue_bikes_data_lake/data/stationdata/station_information-*.parquet'
          options:
            format: PARQUET
