version: 2

sources:
  - name: staging
    database: boston-blue-bikes
    loader: gcloud storage

    tables:
      - name: tripdata
        external:
          location: 'gs://boston_blue_bikes_data_lake/data/tripdata/*.parquet' 
          options:
            format: PARQUET
    
      - name: stationdata
        external:
          location: 'gs://boston_blue_bikes_data_lake/data/stationdata/*.parquet'
          options:
            format: PARQUET


models:
  - name: trips
  - name: stations
  - name: tripdata_testbuild
  - name: stationdata_testbuild
